export const OUTPUT_TYPE = {
    PENDING: 'OUTPUT_TYPE_PENDING',
    CORRECT: 'OUTPUT_TYPE_CORRECT',
    INCORRECT: 'OUTPUT_TYPE_INCORRECT',
    INVALID: 'OUTPUT_TYPE_INVALID'
}

export const USER_ROLE = {
    TEACHER: 'USER_ROLE_TEACHER',
    STUDENT: 'USER_ROLE_STUDENT'
}

export const UNIT_OF_MEASURE = {
    TEMPERATURE: ['KELVIN', 'CELSIUS', 'FAHRENHEIT', 'RANKINE'],
    VOLUME: ['LITERS', 'TABLESPOONS', 'CUBIC_INCHES', 'CUPS', 'CUBIC_FEET', 'GALLONS']
}