export const GET_ALL_PROBLEMS = '[FLEXION] GET ALL PROBLEMS';
export const ADD_PROBLEM = '[FLEXION] ADD PROBLEM';
export const UPDATE_PROBLEM = '[FLEXION] UPDATE PROBLEM';
export const REMOVE_PROBLEM = '[FLEXION] REMOVE PROBLEM';
export const GET_ALL_PROBLEMS_BY_STUDENTS = '[FLEXION] GET ALL PROBLEMS BY STUDENTS';
export const SET_STUDENT_RESPONSE = '[FLEXION] SET STUDENT RESPONSE';