name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: SSH and Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: "ubuntu"
        key: ${{ secrets.EC2_SSH_KEY }}
        # port: ${{ secrets.EC2_PORT }} # Optional, default is 22
        script: |
          cd /var/www/flexion
          sh build-script.sh
          # Any other commands needed for your deployment,
          # like restarting services, running build scripts etc.

# name: Node.js CI/CD with PM2 on AWS EC2

# on:
#   push:
#     branches:
#       - main  # Set the branch on which the CI/CD will run

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3

#     # Deploy to AWS EC2
#     - name: Deploy to AWS EC2
#       env:
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }} # Your EC2 instance SSH private key
#         HOST: ${{ secrets.HOST }} # Public IP or domain of your EC2 instance
#       run: |
#       # Install SSH client
#       sudo apt-get update
#       sudo apt-get install -y openssh-client
#       # Setup SSH key
#       mkdir -p ~/.ssh
#       echo "$EC2_SSH_KEY" > ~/.ssh/github_action_key
#       chmod 600 ~/.ssh/github_action_key
#       # No ssh-keyscan in this version
#       # Connect to EC2 instance and execute commands
#       ssh -o StrictHostKeyChecking=no -i ~/.ssh/github_action_key ubuntu@$HOST "
#         # Navigate to your app directory
#         cd /var/www/flexion
#         # Pull latest code from repository
#         git pull $REPO_URL
#         # Install dependencies
#         npm install
#         # Restart application using PM2
#         pm2 restart all
#       "
 